modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/ElementalWizard/Bedrock-Resources/issues" #optional
logoFile=""
credits="Life"
authors="AlexVR"

[[mods]] #mandatory
modId="tinypals" #mandatory
version="3" #mandatory
displayName="Tiny Pals" #mandatory
description='''Tiny Friends, but dont anger them.
    '''
